linters:
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - gofmt
  disable:
    - forbidigo
    - funlen
    - gci
    - gofumpt
    - govet
    - ireturn
    - prealloc
    - nilnil
    - nlreturn
    - testpackage
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - godox
    - predeclared
    - tagliatelle
    - mnd
  # Enable presets.
  # https://golangci-lint.run/usage/linters
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  # Run only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: true

linters-settings:
  nakedret:
    max-func-lines: 0
  dupl:
    threshold: 155
  cyclop:
    max-complexity: 12

issues:
  exclude-dirs:
    - vendor
    - api_stubs
  exclude-files:
    - .*_test.go