apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    app: {{- include "cloud-native-go.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: "5s"
  SERVER_TIMEOUT_WRITE: "10s"
  SERVER_TIMEOUT_IDLE: "15s"
  SERVER_DEBUG: "true"
  DB_PORT: "5432"
  DB_NAME: "myapp_db"
  DB_HOST: "my-db"
  DB_DEBUG: "true"
