apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  labels:
    app: {{- include "cloud-native-go.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: bXlhcHBfdXNlcg==
  DB_PASS: bXlhcHBfcGFzcw==