apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
spec:
  selector:
    app: {{ .Values.database.name }}
  ports:
  - port: {{ .Values.service.db.port }}