apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{- include "cloud-native-go.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "cloud-native-go.fullname" . }}
  ports:
  - port: {{ .Values.service.app.port }}