apiVersion: batch/v1
kind: Job
metadata:
  name: my-cloud-app-migrate
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: younesi/cloud-native-go:latest
        command: ["/app/bin/migrate", "up"]
        envFrom:
        - configMapRef:
            name: my-cloud-app-config
        - secretRef:
            name: my-cloud-app-secret
      restartPolicy: Never